apiVersion: apps/v1
kind: Deployment
metadata: 
  name: cicd-deploy
  labels:
    app: cicd
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: cicd
  template:
    metadata: 
      labels: 
        app: cicd
    spec:
      containers:
        - name: cicd-deploy
          image: rkatrap/java:latest
          ports:
            - containerPort: 9000